#!/usr/bin/perl -w
use strict;
use warnings;

use Cwd qw(abs_path);

my ($FuncDir, $FuncName) = (abs_path($0) =~ m{^(.*)/(.*)});
my $Verbose = (grep $_ eq'-v', @ARGV)[0] || '';
if ($Verbose) {
    @ARGV = grep $_ ne '-v', @ARGV;
}

chdir $FuncDir;
my @tests = grep /^test_\d{2}$/, <*>;

my @failed;
for my $test (@tests) {
    my $result = `$test $Verbose`;
    if ($?) {
        print "$test FAILED:\n$result\n";
        push @failed, $test;
    }
    else {
        if ($Verbose) {print "$result$test PASSED:\n"; }
        else {print "$test PASSED\n"; }
    }
}
if (@failed) {
    print scalar @failed, " tests failed.\n";
    print(join(', ', @failed), " FAILED\n");
}
exit scalar @failed;

