#!/usr/bin/python3
# ===================================================================
# The contents of this file are dedicated to the public domain.  To
# the extent that dedication to the public domain is not available,
# everyone is granted a worldwide, perpetual, royalty-free,
# non-exclusive license to exercise all rights associated with the
# contents of this file for any purpose whatsoever.
# No rights are reserved.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ===================================================================

USAGE = """USAGE: %s [-t -s -f] inFile outFile [password]
  -t  Run the selftest, print results and exit
  -s  Run the selftest, print results and and save to files, then
      exit
  -f  force write to the output file if it exists.  If not set and the
      output file exists, we abort.
  inFile   the input file
  outFile  the output file
  password the encrypt/decrypt password.  Optional unless inFile or outFile
     is stdin opr stdout.
     We examine the input file and if it is a non-encrypted file, we 
  encrypt the result and send it to outFile.  Likewise, if the input
  is encrypted we decrypt and send the output to outFile.
     '-' for inFile/outFile means send input/output to stdin/stdout.
     If inFile or outFile is to stdin/stdout, a command line password
  must be supplied.
"""

# For debut print input bytes in format similar to old dos debug output.
def bytesToString(bytesIn):
  # indicator for non-ascii chars or non-printable ascii chars...
  NON_PRINT_ASCII = 248 # ø
  rv = ''; i = 0
  # for each 16 byte segment of the input bytes...
  while i < len(bytesIn):
    b = bytesIn[i:i+16]
    b0 = b[0:7]
    b1 = b[8:] if len(b) > 8 else []
    # print hex chars.
    s = "%3d" % (i) + ''.join(" {:02x}".format(x) for x in (b0))
    if b1:
      s += ' |' + ''.join(" {:02x}".format(x) for x in (b1))
    # extend string for formattng.
    while len(s) < 53: s += ' '
    # print ascci or indicate char is NON_PRINT_ASCII.
    for x in (b0):
      s += chr(NON_PRINT_ASCII) if x < ord(' ') or x > ord('~') else chr(x)
    if b1: s += ' | '
    for x in (b1):
      s += chr(NON_PRINT_ASCII) if x < ord(' ') or x > ord('~') else chr(x)
    rv += s
    i += 16
    if i < len(bytesIn): rv += "\n"
  return rv

# class exists so we can check stdin is vim encrypted.  For other
# files we could just seek(0)
class Reader:
  VIM_MAGIC = b'VimCrypt~03!'
  def new (fh): return Reader(fh)
  def __init__(self, fh):
    self.salt = self.seed = ''
    self.fh = fh;
    self.buf = fh.read(1024)
    self.idx = 0
    self.encrypted = self.read(len(VIM_MAGIC)) == VIM_MAGIC
    if self.encrypted:
      self.salt = self.read(8)
      self.seed = self.read(8)
    else:
      self.idx = 0
  def read(self, count):
    if len(self.buf) > 0:
      if (len(self.buf) - count) < 0:
        self.buf += fh.read(1024);
        self.idx = 0;
      rv = self.buf[self.idx:self.idx+count]
      self.idx += len(rv)
    return rv
  def getSeed(self): return self.seed
  def getSalt(self): return self.salt
  def isVimEncrypted(self): return self.encrypted
  def close(): self.fh.close()

from Crypto.Cipher import Blowfish
import struct
swapendian = lambda data: struct.pack('<2L', *struct.unpack('>2L', data))
class Blowfish_ECB:
  def new(key) : return Blowfish_ECB(key)
  def __init__(self, key):
    self.blowfish = Blowfish.new(key, mode=Blowfish.MODE_ECB)
    self.type = ''
  def decrypt(self, ciphertext):
    if self.type:
      if self.type != 'decrypt':
        raise Exception('cipher already used as type: ' + self.type)
    else:
      self.type = 'decrypt'
    return swapendian(self.blowfish.encrypt(swapendian(ciphertext)))
  def encrypt(self, plaintext):
    if self.type:
      if self.type != 'encrypt':
        raise Exception('cipher already used as type: ' + self.type)
    else:
      self.type = 'encrypt'
    return swapendian(self.blowfish.decrypt(swapendian(plaintext)))

import hashlib
def pwToKey(pw, salt):
  for i in range(1000):
    pw = hashlib.sha256(pw.encode() + salt).hexdigest()
  return hashlib.sha256(pw.encode() + salt).digest()

import operator
VIM_MAGIC = b'VimCrypt~03!'
def decrypt(reader, writer, pw):
  if not reader.isVimEncrypted():
    raise Exception('not a blowfish2-encoded vimcrypt file')
  key = pwToKey(pw, reader.getSalt())
  blowfish = Blowfish_ECB.new(key)
  iv = reader.getSeed()
  ciphertext = reader.read(8)
  while ciphertext:
    c0 = blowfish.decrypt(iv)
    plaintext = bytes(map(operator.xor, c0, ciphertext))
    writer.write(plaintext)
    iv = ciphertext
    ciphertext = reader.read(8)

def encrypt(f, writer, pw, salt, seed):
  key = pwToKey(pw, salt)
  blowfish = Blowfish_ECB.new(key)
  writer.write(VIM_MAGIC + salt + seed)
  iv = seed
  plaintext = f.read(8)
  while plaintext:
    c0 = blowfish.decrypt(iv)
    ciphertext = bytes(map(operator.xor, c0, plaintext))
    writer.write(ciphertext)
    iv = ciphertext
    plaintext = f.read(8)

# Using info from a file created using vim with blowfish2, compare
# results encrypting and decrypting the file.
def selfTest(saveResults):
  test_PW = 'hello'
  test_salt = b'\x09\x5b\x17\xda\xdc\xd0\xb7\x16'
  test_seed = b'\x52\x01\xb1\x60\x85\x30\x9a\x7a'
  test_encrypted = b''.join([b'\xfd\xa2\x9e\x94\x7f\xd4\x5f',
    b'\xa6\x4d\xaa\x5e\x39\x6a\x14\x12\xc0',
    b'\x7b\x59\x90\xc5\x54\x5b\x6e\x38\xe9\x6f'])
  testEncrypted = b''.join(
    [VIM_MAGIC, test_salt, test_seed, test_encrypted])
  testPlaintext = b'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

  reader = Reader.new(io.BytesIO(testEncrypted))
  writer = io.BytesIO()
  decrypt(reader, writer, test_PW)
  decrypted = writer.getvalue()
  writer.close()
  if decrypted == testPlaintext:
    print("self test of decryption passed.")
  else:
    print("self test of decryption FAILED.")
    print("testPlaintext:\n" + bytesToString(testPlaintext) + "\n"
      + "decrypted:\n" + bytesToString(decrypted))
  f = io.BytesIO(testPlaintext)
  writer = io.BytesIO()
  encrypt(f, writer, test_PW, test_salt, test_seed)
  encrypted = writer.getvalue()
  writer.close()
  if encrypted == testEncrypted: print("self test of encryption passed.")
  else: print("self test of encryption FAILED.\n"
      + "testEncrypted:\n" + bytesToString(testEncrypted)
      + "\nencrypted:\n" + bytesToString(encrypted))
  encryptedresults = decryptedResults = ''
  if saveResults:
    fName = 'selfTest.encrypted.%s.txt' % (test_PW)
    print ("Saving to " + fName)
    saveTo = open(fName, 'wb'); saveTo.write(encrypted); saveTo.close()
    fName = 'selfTest.plaintext.txt'
    print ("Saving to " + fName)
    saveTo = open(fName, 'wb'); saveTo.write(decrypted); saveTo.close()

import io, os, re, sys
def main(argv=sys.argv):
  global USAGE
  USAGE = USAGE % (os.path.basename(argv[0]))
  USAGE = USAGE.split("\n")
  parseState = 0;
  force = doTest = saveResults = False
  inFile = outFile = password = ''
  try:
    if len(argv) == 1: raise Exception("No arguments given.")
    for i in (range(1,len(argv))):
      arg = argv[i]
      if re.match('^-[stf]$', arg):
        if parseState == 0:
          if arg == '-t':
            doTest = True
          elif arg == '-s':
            saveResults = True
          elif arg == '-f':
            force = True
        else:
          raise Exception("Not a recognized '-' argument:" + arg)
      elif arg == '-':
        if parseState == 0: # inFile
          inFile = arg
          parseState += 1
        elif parseState == 1: # outFile
          outFile = arg
          parseState += 1
        else:
          raise Exception("not a valid argument here: '-'")
      elif parseState == 0: # inFile
        inFile = arg
        parseState += 1
      elif parseState == 1: # outFile
        outFile = arg
        parseState += 1
      elif parseState == 2: # password
        password = arg;

    if doTest or saveResults:
      if inFile or outFile or password:
        raise Exception("if -s or -t, other arguments are not valid.")
      selfTest(saveResults)
      exit(0)
    elif not inFile or not outFile:
      raise Exception("input or outfile not supplied.")
    elif not outFile:
      raise Exception("no output file.")
    elif outFile != '-' and os.isfile(outFile) and not force:
      raise Exception("output file exists and no '-f' arg given.")
    elif (inFile == '-' or outFile == '-') and not password:
      raise Exception(
        'inFile or outFile is stdin/stdout and no password supplied.')
    elif not password:
      password = getpass.getpass('password: ')

    fIn = fOut = ''
    if inFile == '-':
      if sys.stdin.isatty():
        raise Exception('inFile is stdin but stdin is a tty.')
      fIn = sys.stdin
    else:
      fIn = sys.open(inFile, 'rb')
    if outFile == '-':
      if sys.stdout.isatty():
        raise Exception('outFile is stdout but stdout is a tty.')
      fOut = sys.stdout
    else:
      fOut = sys.open(outFile, 'wb')
    reader = Reader.new(fIn)
    if reader.isVimEncrypted():
      decrypted = decrypt(reader)
      encrypt
    exit()

  except Exception as e:
    print( "\n".join(USAGE) + "\n" +  str(e), file=os.sys.stderr)

if __name__ == "__main__":
  main()
